name: SPMB Scraper

on:
  workflow_dispatch:
  schedule:
    - cron: "*/30 * * * *"

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Test Workflow
        run: |
          echo "SPMB Tracker Running"
          date
